# Made by Youri de Vor
#
# Basic makefile which makes the executable which compresses and decompresses the input file and cout's the result.

run:
	g++ *.cpp *.hpp -o lzcompressor

clean:
	rm *.out *.gch compressed.txt lzcompressor
